# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_menu_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiMainMenuWidget(object):
    def setupUi(self, MainMenuWidget):
        MainMenuWidget.setObjectName("MainMenuWidget")
        MainMenuWidget.resize(800, 600)
        self.StartTestBtn = QtWidgets.QPushButton(MainMenuWidget)
        self.StartTestBtn.setGeometry(QtCore.QRect(600, 20, 100, 40))
        self.StartTestBtn.setObjectName("StartTestBtn")
        self.ThemesComboBox = QtWidgets.QComboBox(MainMenuWidget)
        self.ThemesComboBox.setGeometry(QtCore.QRect(20, 20, 500, 40))
        self.ThemesComboBox.setObjectName("ThemesComboBox")

        self.retranslateUi(MainMenuWidget)
        QtCore.QMetaObject.connectSlotsByName(MainMenuWidget)

    def retranslateUi(self, MainMenuWidget):
        _translate = QtCore.QCoreApplication.translate
        MainMenuWidget.setWindowTitle(_translate("MainMenuWidget", "Главное меню"))
        self.StartTestBtn.setText(_translate("MainMenuWidget", "Начать тест"))


class MainMenuWidget(QtWidgets.QWidget, UiMainMenuWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
